# Chain api
chain:
  esc: "https://api.elastos.io/esc"

# Arbiter
arbiter:
  listener: true
  signer: true
  network: "mainnet"
  escStartHeight: 29843440
  escTransactionManagerContractAddress: "0x1f872A1fBc02A38B087DE6af2176ab0BC63a53d0"
  escArbiterManagerContractAddress: "0x9963b5214434776D043A4e98Bc7f33321F6aaCfc"
  escConfigManagerContractAddress: "0x4421c63241A262C423277FFA82C376953072d25f"
  escOrderManagerContractAddress: "0x1f00FEE6B4dbbc97B8c035E1813772C38E64081d"
  escArbiterAddress: "0x3Cf0BB575527cACf9e274a6eE879f876Dae0BC40"
  dataPath: "./app/arbiter/data"
  keyFilePath: "./app/arbiter/data/keys/"
