// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package events

import (
	"github.com/BeL2Labs/Arbiter_Signer/api/events"
)

type ControllerV1 struct{}

func NewV1() events.IEventsV1 {
	return &ControllerV1{}
}
